### ISSUE TITLE
Allowlist IP

### ISSUE THREAD

**Issue by r3g-5z** [Odyssey346/ListenCaddy#3]
There are cases where I'd like to test if the regex (and other stuff) work just fine in a real situation, but I don't want to report my own IP. Or I'd like to keep a universal regex but allowlist an IP that I know will access said blocked path such as an external server.

Current workaround for the former use-case is to just use regex101.com, copy the regex I have, and type in a path and see if it picks it up.

**Comment by Odyssey346** [comment]
So basically a list of IPs that are allowed to visit those paths? Shouldn't be hard to do.

**Comment by r3g-5z** [comment]
Yep! This will avoid me having to remove my reports to my own IP

**Comment by Odyssey346** [comment]
Weird how that commit didn't close the issue. Well, I think I implemented it properly now. Let me know if it doesn't work like you expect.

**Comment by r3g-5z** [comment]
The feature works exactly as I requested, thanks! ❤️
